import { NAME } from './constants';

export const SET_REPOSITORY_OWNER = `${NAME}.SET_REPOSITORY_OWNER`;
export const SET_REPOSITORY_NAME = `${NAME}.SET_REPOSITORY_NAME`;
export const SET_CURRENT_PAGE = `${NAME}.SET_CURRENT_PAGE`;
export const SET_ISSUES = `${NAME}.SET_ISSUES`;
export const RESET_ISSUES_STATE = `${NAME}.RESET_ISSUES_STATE`;
export const RESET_ISSUES_DATA = `${NAME}.RESET_ISSUES_DATA`;
export const SET_LOADING = `${NAME}.SET_LOADING`;
